app = "cartesi-backend"

[build]
image = "registry.fly.io/cartesi-backend-1"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "421614"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0x61f35052e6d3aB5170cc949193B30Dba81127a95"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x31b6CD3ACE5441157d337912374956307E98CCeb"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x3f531E00553D8C60A42e56824822928a2470B7E8"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "2838409"
CARTESI_EPOCH_LENGTH = "43200"